#!/usr/bin/env python3
"""
Constants for Jetson Orin Integration SDK

This file contains all the magic numbers and configuration constants
used throughout the SDK to improve maintainability.

Author: Jetson Orin SDK
"""

# Camera Configuration Constants
CAMERA_USB_DEFAULT_DEVICE = 0
CAMERA_USB_WIDTH = 640
CAMERA_USB_HEIGHT = 480
CAMERA_USB_FPS = 30

CAMERA_CSI_DEFAULT_DEVICE = 0
CAMERA_CSI_WIDTH = 1920
CAMERA_CSI_HEIGHT = 1080
CAMERA_CSI_FPS = 30

CAMERA_IP_DEFAULT_PORT = 8080
CAMERA_IP_TIMEOUT = 10

# LIDAR Configuration Constants
LIDAR_SERIAL_BAUDRATE = 115200
LIDAR_SERIAL_TIMEOUT = 1
LIDAR_SERIAL_BYTESIZE = 8
LIDAR_SERIAL_PARITY = 'N'
LIDAR_SERIAL_STOPBITS = 1

LIDAR_USB_BAUDRATE = 115200
LIDAR_USB_TIMEOUT = 1

LIDAR_ETHERNET_DEFAULT_PORT = 2111
LIDAR_ETHERNET_TIMEOUT = 5

# Alternative Baudrates
LIDAR_BAUDRATE_9600 = 9600
LIDAR_BAUDRATE_230400 = 230400

# Buffer Sizes
LIDAR_BUFFER_SIZE = 1024

# Device Paths
DEVICE_VIDEO_PATTERN = "/dev/video"
DEVICE_TTY_PATTERN = "/dev/tty"

# Network Configuration
DEFAULT_HOST = "192.168.1.100"
DEFAULT_TIMEOUT = 5

# File Operations
DEFAULT_FILE_MODE = "w"
DEFAULT_JSON_INDENT = 2

# Error Codes
ERROR_SUCCESS = 0
ERROR_FAILURE = 1
ERROR_TIMEOUT = 2
ERROR_INVALID_DATA = 3

# Status Codes
STATUS_OK = "OK"
STATUS_ERROR = "ERROR"
STATUS_TIMEOUT = "TIMEOUT"
STATUS_INVALID = "INVALID"
